// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -856044371,
    "text"
  ],
  /* tuple */[
    -459040882,
    "extendedFab"
  ],
  /* tuple */[
    5094087,
    "fab"
  ],
  /* tuple */[
    613841570,
    "outlined"
  ],
  /* tuple */[
    1064531251,
    "contained"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -499495052,
    "secondary"
  ],
  /* tuple */[
    58474434,
    "primary"
  ]
];

function colorToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray$1);
}

function colorFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray$1, param);
}

var IconButton = /* module */[];

exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.colorToJs = colorToJs;
exports.colorFromJs = colorFromJs;
exports.IconButton = IconButton;
/* No side effect */
