// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Forward = /* module */[];

var Back = /* module */[];

exports.Forward = Forward;
exports.Back = Back;
/* No side effect */
