// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -361220291,
    "standard"
  ],
  /* tuple */[
    86969762,
    "filled"
  ],
  /* tuple */[
    613841570,
    "outlined"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -856044371,
    "text"
  ],
  /* tuple */[
    -271659236,
    "email"
  ],
  /* tuple */[
    561678025,
    "number"
  ]
];

function type_ToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray$1);
}

function type_FromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray$1, param);
}

exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.type_ToJs = type_ToJs;
exports.type_FromJs = type_FromJs;
/* No side effect */
