// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");
var Util$KnitZilla = require("./util.bs.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var Core = require("@material-ui/core");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");
var ArrowForwardRounded = require("@material-ui/icons/ArrowForwardRounded");

var headerStyle = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.top(Css.px(25)),
        /* :: */[
          Css.width(/* `percent */[
                -119887163,
                100.0
              ]),
          /* :: */[
            Css.color(Css.hex("fff")),
            /* [] */0
          ]
        ]
      ]
    ]);

var Style = /* module */[/* headerStyle */headerStyle];

function App$Header(Props) {
  return React.createElement(Core.Typography, MaterialUi_Typography.makeProps(undefined, "KnitZilla", headerStyle, undefined, undefined, undefined, undefined, undefined, undefined, /* H3 */16107, undefined, undefined, undefined, undefined, undefined, /* () */0));
}

var Header = /* module */[
  /* Style */Style,
  /* make */App$Header
];

var innerRoot = Css.style(/* :: */[
      Css.padding(Css.px(16)),
      /* :: */[
        Css.position(Css.absolute),
        /* :: */[
          Css.top(/* `percent */[
                -119887163,
                50.0
              ]),
          /* :: */[
            Css.left(/* `percent */[
                  -119887163,
                  50.0
                ]),
            /* :: */[
              Css.transform(Css.translate(/* `percent */[
                        -119887163,
                        -50.0
                      ], /* `percent */[
                        -119887163,
                        -50.0
                      ])),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var floatingNextButton = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.top(/* `percent */[
              -119887163,
              50.0
            ]),
        /* :: */[
          Css.right(Css.px(5)),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* innerRoot */innerRoot,
  /* floatingNextButton */floatingNextButton
];

function nanTest(toTest) {
  var nanTest$1 = Caml_primitive.caml_float_compare(toTest, Number.NaN);
  if (nanTest$1 !== 0) {
    return toTest;
  } else {
    return 0;
  }
}

var initialState = /* record */[
  /* currentMasks */0,
  /* masksToInsert */0
];

function reducer(state, action) {
  if (action.tag) {
    return /* record */[
            /* currentMasks */state[/* currentMasks */0],
            /* masksToInsert */nanTest(action[0])
          ];
  } else {
    return /* record */[
            /* currentMasks */nanTest(action[0]),
            /* masksToInsert */state[/* masksToInsert */1]
          ];
  }
}

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = state[/* currentMasks */0] === 0;
  var match$2 = state[/* masksToInsert */1] === 0;
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: innerRoot
                }, React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(null), undefined, undefined, undefined, /* Column */-81804554, undefined, /* Center */980392437, undefined, undefined, undefined, /* V3 */3, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(React.createElement(Core.TextField, MaterialUi_TextField.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "Antal masker", undefined, undefined, undefined, undefined, (function (e) {
                                            return Curry._1(dispatch, /* SetCurrentMasks */Block.__(0, [e.target.valueAsNumber]));
                                          }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, "number", match$1 ? /* `String */[
                                            -976970511,
                                            ""
                                          ] : /* `Int */[
                                            3654863,
                                            state[/* currentMasks */0]
                                          ], /* Outlined */-28821822, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(React.createElement(Core.TextField, MaterialUi_TextField.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some("Indsæt"), undefined, undefined, undefined, undefined, (function (e) {
                                            return Curry._1(dispatch, /* SetMasksToInsert */Block.__(1, [e.target.valueAsNumber]));
                                          }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, "number", match$2 ? /* `String */[
                                            -976970511,
                                            ""
                                          ] : /* `Int */[
                                            3654863,
                                            state[/* masksToInsert */1]
                                          ], /* Outlined */-28821822, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(React.createElement(Util$KnitZilla.Result[/* make */0], {
                                      results: Util$KnitZilla.calculateMasks(state[/* currentMasks */0], state[/* masksToInsert */1])
                                    })), undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)))), React.createElement("div", {
                  className: floatingNextButton,
                  onClick: (function (_e) {
                      return ReasonReactRouter.push("/calc");
                    })
                }, React.createElement(ArrowForwardRounded.default, { })));
}

var make = App;

exports.Header = Header;
exports.Styles = Styles;
exports.nanTest = nanTest;
exports.initialState = initialState;
exports.reducer = reducer;
exports.make = make;
/* headerStyle Not a pure module */
