// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var App$KnitZilla = require("./App.bs.js");
var Routing$KnitZilla = require("./Routing.bs.js");
var RowCalcRoot$KnitZilla = require("./RowCalcRoot.bs.js");

var root = Css.style(/* :: */[
      Css.height(/* `percent */[
            -119887163,
            100.0
          ]),
      /* :: */[
        Css.width(/* `percent */[
              -119887163,
              100.0
            ]),
        /* :: */[
          Css.position(/* absolute */-1013592457),
          /* :: */[
            Css.backgroundImage(Css.linearGradient(Css.grad(0.0), /* :: */[
                      /* tuple */[
                        Css.px(0),
                        /* `hex */[
                          5194459,
                          "A5A6C5"
                        ]
                      ],
                      /* :: */[
                        /* tuple */[
                          Css.px(100),
                          /* `hex */[
                            5194459,
                            "F8DFC9"
                          ]
                        ],
                        /* [] */0
                      ]
                    ])),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* root */root];

function Root(Props) {
  var route = Routing$KnitZilla.useAppUrl(/* () */0);
  var activeRoute = React.useMemo((function () {
          if (route) {
            return React.createElement(RowCalcRoot$KnitZilla.make, { });
          } else {
            return React.createElement(App$KnitZilla.make, { });
          }
        }), /* array */[route]);
  return React.createElement("div", {
              className: root
            }, React.createElement(App$KnitZilla.Header[/* make */1], { }), activeRoute);
}

var make = Root;

exports.Styles = Styles;
exports.make = make;
/* root Not a pure module */
