// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function routeToPath(route) {
  if (route) {
    return "calc";
  } else {
    return "home";
  }
}

function routeToUrl(route) {
  if (route) {
    return "/calc";
  } else {
    return "/";
  }
}

function useAppUrl(param) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  if (match && match[0] === "calc" && !match[1]) {
    return /* Calc */1;
  } else {
    return /* Home */0;
  }
}

exports.routeToPath = routeToPath;
exports.routeToUrl = routeToUrl;
exports.useAppUrl = useAppUrl;
/* ReasonReactRouter Not a pure module */
