// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Json = require("@glennsl/bs-json/src/Json.bs.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var App$KnitZilla = require("./App.bs.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var Core = require("@material-ui/core");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var RowCalc$KnitZilla = require("./RowCalc.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var ArrowBackRounded = require("@material-ui/icons/ArrowBackRounded");

function decodeRow(jsonString) {
  return /* record */[
          /* title */Json_decode.field("title", Json_decode.string, jsonString),
          /* rows */Json_decode.field("rows", Json_decode.$$int, jsonString)
        ];
}

function decode(jsonString) {
  return Json_decode.array(decodeRow, jsonString);
}

function encodeRow(row) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "title",
                row[/* title */0]
              ],
              /* :: */[
                /* tuple */[
                  "rows",
                  row[/* rows */1]
                ],
                /* [] */0
              ]
            ]);
}

function encode(rows) {
  return Json_encode.array(encodeRow, rows);
}

var RowCalcParser = /* module */[
  /* decodeRow */decodeRow,
  /* decode */decode,
  /* encodeRow */encodeRow,
  /* encode */encode
];

var floatingRightSideBack = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.top(/* `percent */[
              -119887163,
              50.0
            ]),
        /* :: */[
          Css.left(Css.px(5)),
          /* [] */0
        ]
      ]
    ]);

var numberWrapper = Css.style(/* :: */[
      Css.border(Css.px(1), Css.solid, Css.rgba(0, 0, 0, 0.87)),
      /* :: */[
        Css.borderRadius(Css.px(5)),
        /* :: */[
          Css.padding2(Css.px(12), Css.px(24)),
          /* [] */0
        ]
      ]
    ]);

var formControl = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.bottom(/* `percent */[
              -119887163,
              5.0
            ]),
        /* :: */[
          Css.right(/* `percent */[
                -119887163,
                50.0
              ]),
          /* :: */[
            Css.transform(Css.translateX(/* `percent */[
                      -119887163,
                      50.0
                    ])),
            /* [] */0
          ]
        ]
      ]
    ]);

var counterContainer = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            80.0
          ]),
      /* :: */[
        Css.overflowY(Css.auto),
        /* :: */[
          Css.height(/* `percent */[
                -119887163,
                60.0
              ]),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* floatingRightSideBack */floatingRightSideBack,
  /* numberWrapper */numberWrapper,
  /* formControl */formControl,
  /* counterContainer */counterContainer
];

var jsonStringOpt = localStorage.getItem("rowCalcs");

var rows;

if (jsonStringOpt !== null) {
  var match = Json.parse(jsonStringOpt);
  rows = match !== undefined ? Json_decode.array(decodeRow, Caml_option.valFromOption(match)) : /* array */[];
} else {
  rows = /* array */[];
}

var initialState = /* record */[
  /* titleVal */"",
  /* rows */rows
];

function reducer(state, action) {
  if (typeof action === "number") {
    switch (action) {
      case 0 : 
          var newRows = /* array */[/* record */[
              /* title */state[/* titleVal */0],
              /* rows */0
            ]];
          return /* record */[
                  /* titleVal */"",
                  /* rows */$$Array.concat(/* :: */[
                        state[/* rows */1],
                        /* :: */[
                          newRows,
                          /* [] */0
                        ]
                      ])
                ];
      case 1 : 
          return state;
      case 2 : 
          return /* record */[
                  /* titleVal */state[/* titleVal */0],
                  /* rows : array */[]
                ];
      
    }
  } else {
    switch (action.tag | 0) {
      case 0 : 
          var index = action[0];
          var toUpdate = Caml_array.caml_array_get(state[/* rows */1], index);
          Caml_array.caml_array_set(state[/* rows */1], index, /* record */[
                /* title */toUpdate[/* title */0],
                /* rows */toUpdate[/* rows */1] + 1 | 0
              ]);
          return state;
      case 1 : 
          return /* record */[
                  /* titleVal */action[0],
                  /* rows */state[/* rows */1]
                ];
      case 2 : 
          var index$1 = action[0];
          var toUpdate$1 = Caml_array.caml_array_get(state[/* rows */1], index$1);
          Caml_array.caml_array_set(state[/* rows */1], index$1, /* record */[
                /* title */toUpdate$1[/* title */0],
                /* rows */0
              ]);
          return state;
      
    }
  }
}

function RowCalcRoot(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          console.log(state[/* rows */1]);
          localStorage.setItem("rowCalcs", Json.stringify(Json_encode.array(encodeRow, state[/* rows */1])));
          return undefined;
        }), /* array */[state]);
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: App$KnitZilla.Styles[/* innerRoot */0] + (" " + counterContainer)
                }, React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some($$Array.mapi((function (index, a) {
                                    return React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement(RowCalc$KnitZilla.make, {
                                                            rows: a[/* rows */1],
                                                            title: a[/* title */0],
                                                            newValues: (function (action) {
                                                                if (action.tag) {
                                                                  return Curry._1(dispatch, /* UpdateRowReset */Block.__(2, [action[0]]));
                                                                } else {
                                                                  return Curry._1(dispatch, /* UpdateRowIncrement */Block.__(0, [action[0]]));
                                                                }
                                                              }),
                                                            index: index
                                                          })), undefined, undefined, true, /* Column */-81804554, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, String(index), undefined, undefined, undefined, /* () */0));
                                  }), state[/* rows */1])), undefined, undefined, true, /* Column */-81804554, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), React.createElement("div", {
                  className: formControl
                }, React.createElement(Core.Button, MaterialUi_Button.makeProps("+ counter", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                            return Curry._1(dispatch, /* AddNewRow */0);
                          }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Button, MaterialUi_Button.makeProps("Reset", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                            return Curry._1(dispatch, /* Reset */2);
                          }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.TextField, MaterialUi_TextField.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, false, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "Name", undefined, undefined, undefined, undefined, (function (e) {
                            return Curry._1(dispatch, /* ChangeText */Block.__(1, [e.target.value]));
                          }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, "text", /* `String */[
                          -976970511,
                          state[/* titleVal */0]
                        ], undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), React.createElement("div", {
                  className: floatingRightSideBack,
                  onClick: (function (_e) {
                      return ReasonReactRouter.push("/");
                    })
                }, React.createElement(ArrowBackRounded.default, { })));
}

var make = RowCalcRoot;

exports.RowCalcParser = RowCalcParser;
exports.Styles = Styles;
exports.initialState = initialState;
exports.reducer = reducer;
exports.make = make;
/* floatingRightSideBack Not a pure module */
