// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var Core = require("@material-ui/core");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");

var floatingRightSideBack = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.top(/* `percent */[
              -119887163,
              50.0
            ]),
        /* :: */[
          Css.left(Css.px(5)),
          /* [] */0
        ]
      ]
    ]);

var numberWrapper = Css.style(/* :: */[
      Css.border(Css.px(1), Css.solid, Css.rgba(0, 0, 0, 0.87)),
      /* :: */[
        Css.borderRadius(Css.px(5)),
        /* :: */[
          Css.padding2(Css.px(12), Css.px(24)),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* floatingRightSideBack */floatingRightSideBack,
  /* numberWrapper */numberWrapper
];

function rs(prim) {
  return prim;
}

function RowCalc(Props) {
  var rows = Props.rows;
  var title = Props.title;
  var newValues = Props.newValues;
  var index = Props.index;
  return React.createElement(React.Fragment, undefined, React.createElement(Core.Typography, MaterialUi_Typography.makeProps(/* Center */980392437, Caml_option.some(title), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Body1 */-904051921, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(null), undefined, undefined, true, /* Column */-81804554, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement("div", {
                                  className: numberWrapper,
                                  onClick: (function (_e) {
                                      return Curry._1(newValues, /* Count */Block.__(0, [index]));
                                    })
                                }, React.createElement(Core.Typography, MaterialUi_Typography.makeProps(undefined, Caml_option.some(String(rows)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* H6 */16110, undefined, undefined, undefined, undefined, undefined, /* () */0)))), undefined, undefined, true, /* Column */-81804554, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(null), undefined, undefined, true, /* Column */-81804554, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement(Core.Button, MaterialUi_Button.makeProps("+1", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Text */936573133, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                                        console.log("newValues(Count(index))", index);
                                                        return Curry._1(newValues, /* Count */Block.__(0, [index]));
                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, true, /* Column */-81804554, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement(Core.Button, MaterialUi_Button.makeProps("Reset", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Text */936573133, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                                        return Curry._1(newValues, /* Reset */Block.__(1, [index]));
                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, true, /* Column */-81804554, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)))), undefined, undefined, true, /* Column */-81804554, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))));
}

var make = RowCalc;

exports.Styles = Styles;
exports.rs = rs;
exports.make = make;
/* floatingRightSideBack Not a pure module */
