// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var MaterialUi_Color_Blue = require("@jsiebern/bs-material-ui/src/MaterialUi_Color_Blue.bs.js");
var MaterialUi_Color_Amber = require("@jsiebern/bs-material-ui/src/MaterialUi_Color_Amber.bs.js");
var MaterialUi_ThemeOptions = require("@jsiebern/bs-material-ui/src/MaterialUi_ThemeOptions.bs.js");
var Styles = require("@material-ui/core/styles");
var MaterialUi_ThemeProvider = require("@jsiebern/bs-material-ui/src/MaterialUi_ThemeProvider.bs.js");

var theme = Styles.createMuiTheme(MaterialUi_ThemeOptions.make(undefined, undefined, undefined, undefined, Caml_option.some(MaterialUi_ThemeOptions.PaletteOptions[/* make */0](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(MaterialUi_ThemeOptions.Primary[/* make */0](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, MaterialUi_Color_Amber.c100, /* () */0)), Caml_option.some(MaterialUi_ThemeOptions.Secondary[/* make */0](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, MaterialUi_Color_Blue.c100, /* () */0)), undefined, undefined, undefined, /* () */0)), undefined, undefined, undefined, undefined, undefined, Caml_option.some(MaterialUi_ThemeOptions.Typography[/* make */0](undefined, undefined, undefined, undefined, undefined, "Varela Round", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), undefined, /* () */0));

function ThemeProvider(Props) {
  var children = Props.children;
  return React.createElement(MaterialUi_ThemeProvider.make, {
              children: children,
              theme: theme
            });
}

var make = ThemeProvider;

exports.theme = theme;
exports.make = make;
/* theme Not a pure module */
