// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Core = require("@material-ui/core");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");

function calculateMasks(currentMasks, masksToInsertOrRemove) {
  if (currentMasks !== 0) {
    if (masksToInsertOrRemove !== 0) {
      if (masksToInsertOrRemove > currentMasks) {
        return /* array */[];
      } else {
        var temp = currentMasks / masksToInsertOrRemove;
        var floored = Math.floor(temp);
        var ceiled = Math.ceil(temp);
        var diff = temp - floored;
        if (diff > 0.85) {
          return /* array */[ceiled];
        } else if (diff < 0.15) {
          return /* array */[floored];
        } else if (diff === 0) {
          return /* array */[temp];
        } else {
          return /* array */[
                  floored,
                  ceiled
                ];
        }
      }
    } else {
      return /* array */[];
    }
  } else {
    return /* array */[];
  }
}

function Util$Result(Props) {
  var results = Props.results;
  var listLength = results.length;
  if (listLength !== 0) {
    if (listLength !== 1) {
      return $$Array.mapi((function (index, result) {
                    return React.createElement(Core.Typography, MaterialUi_Typography.makeProps(/* Center */980392437, Caml_option.some(" strik 1 maske ind pr " + (String(result) + " maske(r) ")), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, String(index), undefined, undefined, undefined, /* () */0));
                  }), results);
    } else {
      var result = Caml_array.caml_array_get(results, 0);
      return React.createElement(Core.Typography, MaterialUi_Typography.makeProps(/* Center */980392437, Caml_option.some(" Strik 1 maske ind pr " + (String(result) + " maske(r) ")), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0));
    }
  } else {
    return React.createElement(Core.Typography, MaterialUi_Typography.makeProps(/* Center */980392437, "Intet at udregne endnu", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0));
  }
}

var Result = /* module */[/* make */Util$Result];

exports.calculateMasks = calculateMasks;
exports.Result = Result;
/* react Not a pure module */
